kind: Deployment
apiVersion: apps/v1
metadata:
  name: mongodb-express
  namespace: default
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: mongodb-express
  template:
    metadata:
      labels:
        app: mongodb-express
    spec:
      containers:
        - name: mongo-express
          image: mongo-express:latest
          env:
            - name: ME_CONFIG_SITE_BASEURL
              value: /ui/mongodb-express
            - name: ME_CONFIG_MONGODB_SERVER
              value: mongo-0.mongo,mongo-1.mongo,mongo-2.mongo
            - name: ME_CONFIG_MONGODB_PORT
              value: "27017"
          ports:
            - name: mongoxweb
              containerPort: 8081

---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-express-svc
  namespace: default
  labels:
    app: mongodb-express
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: mongoxweb
      protocol: TCP
  selector:
    app: mongodb-express

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mongodb-express-ingress
  namespace: default
  annotations:
    kubernetes.io/ingress.class: nginx
    # nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - http:
        paths:
          - path: /ui/mongodb-express
            pathType: Prefix
            backend:
              service:
                name: mongodb-express-svc
                port:
                  name: http
